[[headers]]
  for = "/*"  # 모든 경로에 대해 적용
  [headers.values]
    Access-Control-Allow-Origin = "*"  # 모든 도메인에서 접근 허용
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"  # 허용할 HTTP 메서드
    Access-Control-Allow-Headers = "Content-Type"  # 허용할 헤더